import React from 'react'
import { useNavigate } from 'react-router-dom'
import { Zap, ArrowLeft } from 'lucide-react'

export default function Terms() {
  const navigate = useNavigate()

  const sections = [
    {
      title: '1. Acceptance of Terms',
      body: `By accessing or using Evoke CMO ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Platform.\n\nEvoke CMO is an AI-powered marketing platform that helps businesses generate and publish multi-channel marketing campaigns across social media platforms.`,
    },
    {
      title: '2. Eligibility',
      body: `You must be at least 18 years old and have the legal capacity to enter into a binding agreement to use Evoke CMO. By using the Platform, you represent and warrant that you meet these requirements.\n\nBusinesses using the Platform must have the legal authority to post content on behalf of their organisation.`,
    },
    {
      title: '3. Account Registration',
      body: `To access certain features of the Platform, you must register for an account. You agree to:\n\n• Provide accurate, current, and complete information during registration\n• Maintain and promptly update your account information\n• Keep your password secure and confidential\n• Notify us immediately of any unauthorised use of your account\n• Be responsible for all activities that occur under your account`,
    },
    {
      title: '4. Use of the Platform',
      body: `You agree to use Evoke CMO only for lawful purposes and in accordance with these Terms. You agree NOT to:\n\n• Post content that is illegal, harmful, threatening, abusive, or defamatory\n• Violate any third-party platform's terms of service (Facebook, Instagram, LinkedIn, TikTok, etc.)\n• Upload content that infringes any intellectual property rights\n• Use the Platform to send spam or unsolicited messages\n• Attempt to gain unauthorised access to any part of the Platform\n• Use the Platform to distribute malware or harmful code`,
    },
    {
      title: '5. Social Media Integrations',
      body: `Evoke CMO connects to third-party social media platforms including Facebook, Instagram, LinkedIn, TikTok, and WhatsApp. By connecting these accounts:\n\n• You authorise Evoke CMO to post content on your behalf\n• You remain responsible for all content posted through the Platform\n• You must comply with each platform's own terms of service and community guidelines\n• We are not responsible for any actions taken by third-party platforms regarding your accounts`,
    },
    {
      title: '6. AI-Generated Content',
      body: `Evoke CMO uses artificial intelligence to generate marketing content. You acknowledge that:\n\n• AI-generated content may not always be accurate, appropriate, or suitable for your needs\n• You are responsible for reviewing all AI-generated content before it is published\n• Evoke CMO does not guarantee the accuracy, completeness, or fitness of AI-generated content\n• You retain full responsibility for any content published through the Platform`,
    },
    {
      title: '7. Tokens and Payments',
      body: `Evoke CMO operates on a token-based system. Tokens are required to generate and post campaigns.\n\n• Tokens are purchased and credited to your account\n• Tokens are non-refundable once used\n• Unused tokens do not expire but have no cash value\n• We reserve the right to modify token pricing at any time with prior notice\n• All payments are processed securely through our payment partners`,
    },
    {
      title: '8. Intellectual Property',
      body: `The Evoke CMO platform, including its design, code, features, and branding, is owned by Evoke CMO and protected by intellectual property laws.\n\nYou retain ownership of any original content you upload to the Platform. By uploading content, you grant Evoke CMO a limited licence to use that content solely to provide the services you request.\n\nAI-generated content produced by the Platform may be used by you for your marketing purposes.`,
    },
    {
      title: '9. Privacy',
      body: `Your use of Evoke CMO is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Please review our Privacy Policy at evoke-cmo-frontend.vercel.app/privacy to understand our practices.`,
    },
    {
      title: '10. Limitation of Liability',
      body: `To the maximum extent permitted by law, Evoke CMO shall not be liable for:\n\n• Any indirect, incidental, special, or consequential damages\n• Loss of profits, data, or business opportunities\n• Damages arising from your use or inability to use the Platform\n• Actions taken by third-party social media platforms on your accounts\n• Any content generated by AI that causes harm or loss\n\nOur total liability to you shall not exceed the amount you paid us in the 3 months preceding the claim.`,
    },
    {
      title: '11. Termination',
      body: `We reserve the right to suspend or terminate your account at any time if you:\n\n• Violate these Terms of Service\n• Engage in fraudulent or harmful activity\n• Use the Platform in a way that could cause legal liability\n\nYou may terminate your account at any time by contacting us. Upon termination, your right to use the Platform ceases immediately.`,
    },
    {
      title: '12. Changes to Terms',
      body: `We may update these Terms of Service from time to time. We will notify you of significant changes by email or through the Platform. Continued use of Evoke CMO after changes constitutes acceptance of the updated Terms.\n\nWe recommend reviewing these Terms periodically.`,
    },
    {
      title: '13. Governing Law',
      body: `These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts in India.`,
    },
    {
      title: '14. Contact Us',
      body: `If you have any questions about these Terms of Service, please contact us:\n\nEmail: vasanthchowdarythumati@gmail.com\nPlatform: evoke-cmo-frontend.vercel.app`,
    },
  ]

  return (
    <div style={{ minHeight: '100vh', background: '#0a0a0a', color: '#fff', fontFamily: 'Inter, sans-serif' }}>
      {/* Header */}
      <div style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '0 32px' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', height: 64, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }} onClick={() => navigate('/')}>
            <Zap size={20} style={{ color: '#7c3aed' }} />
            <span style={{ fontWeight: 800, fontSize: 16 }}>Evoke CMO</span>
          </div>
          <button
            onClick={() => navigate(-1)}
            style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 8, padding: '6px 14px', color: 'rgba(255,255,255,0.6)', fontSize: 13, cursor: 'pointer' }}
          >
            <ArrowLeft size={14} /> Back
          </button>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 800, margin: '0 auto', padding: '64px 24px 80px' }}>
        <h1 style={{ fontSize: 42, fontWeight: 900, letterSpacing: '-0.03em', marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: 15, marginBottom: 48 }}>
          Last updated: {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 36 }}>
          {sections.map((s, i) => (
            <div key={i}>
              <h2 style={{ fontSize: 18, fontWeight: 700, color: '#a78bfa', marginBottom: 12 }}>{s.title}</h2>
              <p style={{ color: 'rgba(255,255,255,0.65)', fontSize: 15, lineHeight: 1.8, whiteSpace: 'pre-line' }}>{s.body}</p>
            </div>
          ))}
        </div>

        <div style={{ marginTop: 56, padding: '24px 28px', background: 'rgba(124,58,237,0.08)', border: '1px solid rgba(124,58,237,0.25)', borderRadius: 14 }}>
          <p style={{ color: 'rgba(255,255,255,0.5)', fontSize: 14, lineHeight: 1.7 }}>
            These Terms of Service were last updated on {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}.
            If you have questions, email us at <a href="mailto:vasanthchowdarythumati@gmail.com" style={{ color: '#a78bfa' }}>vasanthchowdarythumati@gmail.com</a>
          </p>
        </div>
      </div>
    </div>
  )
}
